# Generated by Django 3.1.1 on 2020-09-11 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0002_notemodle_the_tweet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodle',
            name='the_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
